dependencies:
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.2.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
networks:
  default: "development"
  development:
    key_hash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
  rinkeby:
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    chainlink_subscription_id: "4158"
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    key_hash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
