dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
networks:
  default: "development"
  rinkeby:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
